# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3fovwhcDKELLb8FagVE2PdsiwizAXsE
"""

def constBoard(board):
    print("Current status of the board:\n")
    for i in range(0, 9):
        if i > 0 and i % 3 == 0:
            print("\n")
        if board[i] == 0:
            print("_", end=" ")
        elif board[i] == 1:
            print("X", end=" ")
        elif board[i] == -1:
            print("O", end=" ")
    print("\n")


def user1turn(board):
    position = int(input("Enter the 0's position from [1, 2, ..., 9]: "))
    if board[position - 1] != 0:
        print("Wrong move")
        exit(0)
    board[position - 1] = -1


def user2turn(board):
    position = int(input("Enter the X's position from [1, 2, ..., 9]: "))
    if board[position - 1] != 0:
        print("Wrong move")
        exit(0)
    board[position - 1] = 1


def minmax(board, player):
    x = analyzeboard(board)
    if x != 0:
        return x * player
    position = -1
    value = -2
    for i in range(0, 9):
        if board[i] == 0:
            board[i] = player
            score = -minmax(board, player * -1)
            board[i] = 0
            if score > value:
                value = score
                position = i
    if position == -1:
        return 0
    return value


def AIturn(board):
    position = -1
    value = -2
    for i in range(0, 9):
        if board[i] == 0:
            board[i] = 1
            score = -minmax(board, -1)
            board[i] = 0
            if score > value:
                value = score
                position = i
    board[position] = 1


def analyzeboard(board):
    cb = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]]

    for i in range(0, 8):
        if board[cb[i][0]] == board[cb[i][1]] == board[cb[i][2]] and board[cb[i][0]] != 0:
            return board[cb[i][0]]
    return 0


def main():
    choice = int(input("Enter 1 for playing with AI and 2 for playing with friends: "))
    board = [0, 0, 0, 0, 0, 0, 0, 0, 0]

    print("Current status of the board:\n")
    for i in range(0, 9):
        if i > 0 and i % 3 == 0:
            print("\n")
        print("_", end=" ")

    if choice == 1:
        print("\n\nThanks for choosing to play:")
        print("Welcome to the Game. You are playing with AI")
        player = int(input("Who wants to start the game? Press 1 for your Turn and 2 for AI turn: "))
        for i in range(0, 9):
            if analyzeboard(board) != 0:
                break
            if (i + player) % 2 == 0:
                AIturn(board)
            else:
                constBoard(board)
                user1turn(board)
    else:
        print("\n\nThanks for choosing to play:")
        print("Welcome to the Game. You are playing with a friend")
        for i in range(0, 9):
            if analyzeboard(board) != 0:
                break
            if i % 2 == 0:
                constBoard(board)
                user1turn(board)
            else:
                constBoard(board)
                user2turn(board)

    che = analyzeboard(board)
    constBoard(board)

    if che == 0:
        print("Game is a draw.")
    elif che == -1:
        print("0 wins and X loses.")
    elif che == 1:
        print("X wins and 0 loses.")


main()